import React, { createContext, useContext, useState } from "react";

export const LANGUAGES = [
  { code: "en", label: "English", native: "English", flag: "🇬🇧" },
  { code: "am", label: "Amharic", native: "አማርኛ", flag: "🇪🇹" },
  { code: "or", label: "Afan Oromo", native: "Afaan Oromoo", flag: "🇪🇹" },
];

export const TRANSLATIONS = {
  en: {
    home: "Home",
    routes: "Routes",
    operators: "Operators",
    about: "About",
    dashboard: "Dashboard",
    bookJourney: "Book a Journey",
    departingFrom: "DEPARTING FROM",
    arrivingAt: "ARRIVING AT",
    searchRoutes: "Search Routes",
    selectOrigin: "Select origin",
    selectDestination: "Select destination",
    routesSchedules: "Routes & Schedules",
    noRoutes: "No routes match your search.",
    tryDifferent: "Try a different origin or destination.",
    departures: "DEPARTURES FOUND",
    loading: "LOADING…",
    allClasses: "All classes",
    luxury: "Luxury",
    established: "Established",
    electric: "Electric",
    earliest: "Earliest departure",
    cheapest: "Lowest fare",
    fastest: "Fastest",
    seats: "seats",
    bookNow: "Book Now",
    selectSeat: "Select Your Seat",
    passengerDetails: "Passenger Details",
    payment: "Payment",
    yourTicket: "Your Ticket",
    passengerName: "FULL NAME",
    phone: "TELEBIRR PHONE NUMBER",
    agentPhone: "CUSTOMER PHONE NUMBER",
    proceedTelebirr: "Proceed to Telebirr",
    confirmDetails: "Confirm Details",
    fullRefund: "FULL REFUND",
    halfRefund: "50% REFUND",
    noRefund: "NO REFUND",
    fullRefundDesc: "> 24h before",
    halfRefundDesc: "18h – 24h before",
    noRefundDesc: "< 18h before",
    savePhotos: "Save to Photos",
    sendTelegram: "Send to Telegram",
    scanBoarding: "SCAN AT BOARDING",
    validId: "VALID ID REQUIRED",
    language: "Language",
  },
  am: {
    home: "መነሻ",
    routes: "መስመሮች",
    operators: "አሠሪዎች",
    about: "ስለኛ",
    dashboard: "ዳሽቦርድ",
    bookJourney: "ጉዞ ያስይዙ",
    departingFrom: "የሚነሱበት",
    arrivingAt: "የሚደርሱበት",
    searchRoutes: "መስመሮችን ፈልጉ",
    selectOrigin: "መነሻ ይምረጡ",
    selectDestination: "መድረሻ ይምረጡ",
    routesSchedules: "መስመሮች እና መርሃ ግብሮች",
    noRoutes: "ለፍለጋዎ የሚዛምዱ መስመሮች አልተገኙም።",
    tryDifferent: "ሌላ መነሻ ወይም መድረሻ ሞክሩ።",
    departures: "ጉዞዎች ተገኝተዋል",
    loading: "እየጫነ ነው…",
    allClasses: "ሁሉም ክፍሎች",
    luxury: "ዘመናዊ",
    established: "ታዋቂ",
    electric: "ኤሌክትሪክ",
    earliest: "ቀደምት ጉዞ",
    cheapest: "ዝቅተኛ ዋጋ",
    fastest: "ፈጣን",
    seats: "ወንበሮች",
    bookNow: "አሁን ያስይዙ",
    selectSeat: "ወንበር ይምረጡ",
    passengerDetails: "የተሳፋሪ መረጃ",
    payment: "ክፍያ",
    yourTicket: "የእርስዎ ቲኬት",
    passengerName: "ሙሉ ስም",
    phone: "የቴሌብር ስልክ ቁጥር",
    agentPhone: "የደንበኛ ስልክ ቁጥር",
    proceedTelebirr: "ወደ ቴሌብር ይሂዱ",
    confirmDetails: "ዝርዝር ያረጋግጡ",
    fullRefund: "ሙሉ ተመላሽ",
    halfRefund: "50% ተመላሽ",
    noRefund: "ምንም ተመላሽ የለም",
    fullRefundDesc: "ከ24 ሰዓት በላይ",
    halfRefundDesc: "18 – 24 ሰዓት",
    noRefundDesc: "ከ18 ሰዓት በታች",
    savePhotos: "ፎቶዎች ላይ ያስቀምጡ",
    sendTelegram: "ወደ ቴሌግራም ይላኩ",
    scanBoarding: "ሲሳፈሩ ያስቃኙ",
    validId: "ህጋዊ መታወቂያ ያስፈልጋል",
    language: "ቋንቋ",
  },
  or: {
    home: "Mana",
    routes: "Karaalee",
    operators: "Hojjettoota",
    about: "Waa'ee Keenya",
    dashboard: "Daashboordii",
    bookJourney: "Imala Kuusaa",
    departingFrom: "Ka'UMSA",
    arrivingAt: "GARA",
    searchRoutes: "Karaalee Barbaadi",
    selectOrigin: "Ka'umsa filadhu",
    selectDestination: "Gara filadhu",
    routesSchedules: "Karaalee fi Sagantaalee",
    noRoutes: "Karaalee barbaacha keessaniif hin argamne.",
    tryDifferent: "Ka'umsa ykn gara biraa yaalaa.",
    departures: "DEEMSA ARGAME",
    loading: "Fe'aa jira…",
    allClasses: "Kutaalee hunda",
    luxury: "Ammayyaa",
    established: "Beekamaa",
    electric: "Elektirikii",
    earliest: "Deemsa duraa",
    cheapest: "Gatii gadi aanaa",
    fastest: "Ariifataa",
    seats: "teessoolee",
    bookNow: "Amma Kuusi",
    selectSeat: "Teessoo Filadhu",
    passengerDetails: "Odeeffannoo Imaltuu",
    payment: "Kaffaltii",
    yourTicket: "Tikeetii Keessan",
    passengerName: "MAQAA GUUTUU",
    phone: "LAKKOOFSA BILBILAA TELEBIRR",
    agentPhone: "LAKKOOFSA BILBILAA MAAMILA",
    proceedTelebirr: "Gara Telebirr Deemuuf",
    confirmDetails: "Odeeffannoo Mirkaneessi",
    fullRefund: "DEEBII GUUTUU",
    halfRefund: "DEEBII 50%",
    noRefund: "DEEBII HIN JIRU",
    fullRefundDesc: "> Saatii 24 dura",
    halfRefundDesc: "Saatii 18 – 24",
    noRefundDesc: "< Saatii 18 dura",
    savePhotos: "Suuraa Keessatti Olkaa'i",
    sendTelegram: "Gara Telegram Ergi",
    scanBoarding: "FI'AMSIISA YEROO YAABBATU",
    validId: "EENYUMMAA SIRRII BARBAACHISA",
    language: "Afaan",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("ak_lang") || "en");

  const switchLang = (code) => {
    setLang(code);
    localStorage.setItem("ak_lang", code);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}