// Enriched operator profile data for the operator showcase pages

export const SEATING_RULE = {
  type: "FCFS",
  label: "First Come, First Served",
  description: "Seats are assigned in order of booking confirmation. The earlier you book, the lower your seat number. No seat selection — your seat is auto-assigned at the moment of payment.",
};

export const OPERATOR_PROFILES = {
  "Selam Bus": {
    slug: "selam-bus",
    name: "Selam Bus",
    klass: "luxury",
    tagline: "Ethiopia's Premier Long-Haul Network",
    gallery: [
      "https://selambus.wordpress.com/wp-content/uploads/2015/09/superdecks.jpg",
      "https://selambus.wordpress.com/wp-content/uploads/2015/09/collecting-luggae-from-selam-bus.jpg",
      "https://selambus.wordpress.com/wp-content/uploads/2015/09/steve-and-shelagh-at-selam-bus.jpg",
    ],
    est: "1996",
    headquarters: "Addis Ababa",
    employees: "2,000+",
    fleetSize: "120+ buses",
    website: null,
    safetyRating: 4.8,
    passengerRating: 4.6,
    punctualityRating: 4.5,
    totalTrips: "500,000+",
    desc: "Ethiopia's largest intercity network, operating since 1996 with modern Scania Marcopolo buses featuring full air conditioning and entertainment systems. Selam Bus has set the gold standard for long-distance travel across the Ethiopian highlands.",
    fleet: [
      { model: "Scania Marcopolo Paradiso", count: 60, capacity: 51, year: "2019–2023", type: "Luxury Coach" },
      { model: "Scania Marcopolo Viaggio", count: 40, capacity: 49, year: "2016–2018", type: "Semi-Luxury" },
      { model: "Scania K410", count: 20, capacity: 55, year: "2021–2023", type: "Express" },
    ],
    amenities: ["Air Conditioning", "Reclining Seats", "Entertainment", "Safety Belts", "Charging Ports"],
    safetyFeatures: [
      "GPS-tracked fleet 24/7",
      "Mandatory driver rest stops every 4 hours",
      "Pre-departure vehicle safety inspection",
      "Emergency exits on every vehicle",
      "Fire extinguisher & first aid kit onboard",
      "Certified drivers with 5+ years experience",
    ],
    routes: ["Addis Ababa → Mekelle", "Addis Ababa → Bahir Dar", "Addis Ababa → Gondar", "Addis Ababa → Harar", "Addis Ababa → Arbaminch"],
    certifications: ["Ethiopian Transport Authority Certified", "ISO 9001:2015", "East Africa Road Safety Award 2022"],
    color: "primary",
  },
  "ODAA Integrated": {
    slug: "odaa-integrated",
    name: "ODAA Integrated",
    klass: "luxury",
    tagline: "Ultra-Modern Volvo Highland Cruisers",
    gallery: [
      "https://www.odaabus.net/img/slide_img/2.jpg",
      "https://www.odaabus.net/img/slide_img/1.jpg",
      "https://www.odaabus.net/img/portfolio/03.jpg",
      "https://www.odaabus.net/img/portfolio/04.jpg",
    ],
    est: "2018",
    headquarters: "Addis Ababa",
    employees: "800+",
    fleetSize: "50+ buses",
    website: null,
    safetyRating: 4.9,
    passengerRating: 4.7,
    punctualityRating: 4.8,
    totalTrips: "120,000+",
    desc: "A 400-million-Birr fleet of ultra-modern Volvo buses delivering premium cross-country services across the highlands. ODAA Integrated is redefining luxury travel in Ethiopia with state-of-the-art Swedish engineering.",
    fleet: [
      { model: "Volvo B11R Marcopolo", count: 30, capacity: 49, year: "2020–2024", type: "Ultra-Luxury Coach" },
      { model: "Volvo B8R", count: 20, capacity: 45, year: "2022–2023", type: "Luxury Coach" },
    ],
    amenities: ["Air Conditioning", "2x2 Reclining", "Entertainment", "Safety Belts", "Charging Ports", "Wi-Fi", "Toilet"],
    safetyFeatures: [
      "Volvo Dynamic Steering system",
      "Automatic Emergency Braking (AEB)",
      "Real-time telemetry and driver monitoring",
      "Alcohol interlocks on all vehicles",
      "Fatigue detection system",
      "Full CCTV coverage inside & outside",
    ],
    routes: ["Addis Ababa → Mekelle", "Addis Ababa → Gondar", "Addis Ababa → Nekemte"],
    certifications: ["Ethiopian Transport Authority Certified", "Volvo Safety Excellence Partner", "East Africa Premium Operator 2023"],
    color: "accent",
  },
  "Zemen Bus": {
    slug: "zemen-bus",
    name: "Zemen Bus",
    klass: "luxury",
    tagline: "Modern Coaches. Connected Journeys.",
    gallery: [],
    est: "2012",
    headquarters: "Addis Ababa",
    employees: "600+",
    fleetSize: "40+ buses",
    website: null,
    safetyRating: 4.6,
    passengerRating: 4.5,
    punctualityRating: 4.4,
    totalTrips: "200,000+",
    desc: "Modern Golden Dragon coaches imported from China with free Wi-Fi, charging ports, and full entertainment on every journey. Zemen Bus blends connectivity with comfort for the modern Ethiopian traveller.",
    fleet: [
      { model: "Golden Dragon XML6126", count: 25, capacity: 45, year: "2019–2022", type: "Luxury Coach" },
      { model: "Golden Dragon XML6112", count: 15, capacity: 41, year: "2018–2020", type: "Semi-Luxury" },
    ],
    amenities: ["Air Conditioning", "2x2 Reclining", "Free Wi-Fi", "Charging Ports", "Entertainment", "Safety Belts"],
    safetyFeatures: [
      "Wi-Fi connected GPS tracking",
      "Driver behavior monitoring software",
      "Monthly vehicle inspections",
      "Emergency brake assist",
      "Fire suppression system",
      "Trained emergency response crew",
    ],
    routes: ["Addis Ababa → Bahir Dar", "Addis Ababa → Hawassa", "Addis Ababa → Mekelle"],
    certifications: ["Ethiopian Transport Authority Certified", "Golden Dragon Safety Standard"],
    color: "primary",
  },
  "Yegna Bus": {
    slug: "yegna-bus",
    name: "Yegna Bus",
    klass: "luxury",
    tagline: "Premium Service. Every Mile.",
    gallery: [],
    est: "2018",
    headquarters: "Addis Ababa",
    employees: "400+",
    fleetSize: "30+ buses",
    website: null,
    safetyRating: 4.7,
    passengerRating: 4.8,
    punctualityRating: 4.6,
    totalTrips: "80,000+",
    desc: "Premium operator with onboard chargers, toilets, Wi-Fi, and complimentary breakfast service on long-haul routes. Yegna Bus believes every passenger deserves a first-class experience regardless of destination.",
    fleet: [
      { model: "Higer KLQ6125", count: 20, capacity: 47, year: "2021–2024", type: "Premium Coach" },
      { model: "Higer KLQ6109", count: 10, capacity: 43, year: "2019–2021", type: "Luxury Coach" },
    ],
    amenities: ["Air Conditioning", "Reclining Seats", "Free Wi-Fi", "Charging Ports", "Toilet", "Breakfast", "Entertainment"],
    safetyFeatures: [
      "Complimentary travel insurance coverage",
      "Speed governors capped at 80 km/h on highways",
      "Driver alertness monitoring",
      "24/7 passenger helpline",
      "Luggage tracking and secure storage",
      "Night-travel safety protocols",
    ],
    routes: ["Addis Ababa → Mekelle", "Addis Ababa → Gondar", "Addis Ababa → Hawassa"],
    certifications: ["Ethiopian Transport Authority Certified", "Customer Excellence Award 2023"],
    color: "accent",
  },
  "Velocity Express": {
    slug: "velocity-express",
    name: "Velocity Express",
    klass: "electric",
    tagline: "Zero Emissions. Infinite Horizons.",
    gallery: [],
    est: "2024",
    headquarters: "Addis Ababa",
    employees: "500+",
    fleetSize: "100 electric buses",
    website: null,
    safetyRating: 5.0,
    passengerRating: 4.9,
    punctualityRating: 4.7,
    totalTrips: "15,000+",
    desc: "East Africa's largest electric bus project — 100% electric, zero emissions, leading the future of sustainable Ethiopian transport. Velocity Express is committed to green mobility and a cleaner tomorrow.",
    fleet: [
      { model: "Golden Dragon XML6125JEVK5", count: 100, capacity: 40, year: "2024", type: "Electric Coach" },
    ],
    amenities: ["100% Electric", "Zero Emissions", "Air Conditioning", "Charging Ports", "Free Wi-Fi", "Comfortable Seating", "Entertainment"],
    safetyFeatures: [
      "Battery Management System (BMS) with thermal runaway protection",
      "Regenerative braking on all vehicles",
      "Real-time battery health monitoring",
      "Over-the-air software safety updates",
      "Collision avoidance radar",
      "Full interior CCTV and passenger sensors",
    ],
    routes: ["Various routes across Ethiopia"],
    certifications: ["Ethiopian Transport Authority Certified", "Green Transport Initiative 2024", "East Africa EV Pioneer Award"],
    color: "accent",
  },
  "Golden Bus": {
    slug: "golden-bus",
    name: "Golden Bus",
    klass: "established",
    tagline: "Reliable Routes. Trusted Since 2016.",
    gallery: [],
    est: "2016",
    headquarters: "Addis Ababa",
    employees: "350+",
    fleetSize: "20+ buses",
    website: null,
    safetyRating: 4.5,
    passengerRating: 4.4,
    punctualityRating: 4.3,
    totalTrips: "150,000+",
    desc: "Luxury long-distance services connecting Addis Ababa to eastern and southern destinations since 2016. Golden Bus has built a loyal passenger base through reliability, fair pricing, and consistent service quality.",
    fleet: [
      { model: "King Long XMQ6130", count: 12, capacity: 45, year: "2018–2022", type: "Luxury Coach" },
      { model: "King Long XMQ6112", count: 10, capacity: 43, year: "2016–2018", type: "Semi-Luxury" },
    ],
    amenities: ["Air Conditioning", "Reclining Seats", "Safety Belts", "Charging Ports"],
    safetyFeatures: [
      "Regular mechanical inspection every 10,000 km",
      "Licensed and certified drivers only",
      "Speed monitoring and alerts",
      "Emergency contact system",
      "Passenger manifest system",
    ],
    routes: ["Addis Ababa → Hawassa", "Addis Ababa → Jijiga", "Addis Ababa → Harar"],
    certifications: ["Ethiopian Transport Authority Certified"],
    color: "primary",
  },
};

export function getOperatorBySlug(slug) {
  return Object.values(OPERATOR_PROFILES).find((op) => op.slug === slug) || null;
}